version: '2.1'
services:
  dirserver:
    container_name: 'dirserver'
    networks:
      dirwatcher:
        ipv4_address: 172.12.1.10
    build:
      context: '.'
      dockerfile: './cmd/dirserver/Dockerfile'
    restart: on-failure
    ports:
      - '8080:8080'
    volumes:
      - '.:/go/src/dirwatcher'
    depends_on:
      - 'rabbitmq'
  rabbitmq:
    image: 'rabbitmq:3.7'
    networks:
      dirwatcher:
        ipv4_address: 172.12.1.2
    container_name: 'rabbitmq'
    ports:
      - '25672:5672'
networks:
    dirwatcher:
        ipam:
            driver: default
            config:
                - subnet: 172.12.1.0/24

